POST  http://localhost:3003/api/blogs/
content-type: application/json
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYyNWY3NmZiMzNlNWJmZTMwYjNjYWZkZSIsImlhdCI6MTY1MDQyMzYwOX0.9I5KU8ibdj5woxHTaIRs6ezeN_yFg0r44mLXtOjCcb8    

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 0
}